name: Paper Trader (ChartScanAI)

on:
  schedule:
    # 09:35 ET during Daylight (UTC-4)
    - cron: "35 13 * * 1-5"
    # 09:35 ET during Standard (UTC-5)
    - cron: "35 14 * * 1-5"
  workflow_dispatch: {}
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache PyTorch CPU wheels
        uses: actions/cache@v4
        with:
          path: ~/.cache/torch
          key: ${{ runner.os }}-torch-cpu-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-torch-cpu-

      - name: Cache model weights
        uses: actions/cache@v4
        with:
          path: weights/
          key: ${{ runner.os }}-model-weights-${{ hashFiles('weights/**') }}
          restore-keys: |
            ${{ runner.os }}-model-weights-

      - name: Install deps (CPU)
        run: |
          python -m pip install --upgrade pip
          pip install --extra-index-url https://download.pytorch.org/whl/cpu "torch>=2.3,<3" "torchvision>=0.18,<1"
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install ultralytics yfinance mplfinance pandas numpy pillow alpaca-py; fi

      - name: Verify model file exists
        run: |
          if [ ! -f "weights/custom_yolov8.pt" ]; then
            echo "ERROR: Model file weights/custom_yolov8.pt not found!"
            echo "Please ensure the model file is committed to the repository."
            exit 1
          fi
          echo "Model file found: $(ls -la weights/custom_yolov8.pt)"

      - name: Run trader (DRY RUN if no secrets)
        env:
          ALPACA_API_KEY_ID: ${{ secrets.ALPACA_API_KEY_ID }}
          ALPACA_API_SECRET_KEY: ${{ secrets.ALPACA_API_SECRET_KEY }}
        run: |
          echo "Starting ChartScanAI Paper Trader..."
          python paper_trader_fast.py
          echo "Paper trader completed successfully."

      - name: Commit artifacts
        run: |
          git config user.name "chartscan-bot"
          git config user.email "chartscan-bot@users.noreply.github.com"
          
          # Check if there are any changes to commit
          if git diff --quiet && git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git add daily_runs/ paper_state.json || true
            git commit -m "chore(run): paper bot artifacts $(date -u +'%Y-%m-%d %H:%M:%SZ')" || echo "No changes to commit"
            git push
          fi
